### ISSUE TITLE
Failed to activate the go-to-view package

### ISSUE THREAD

**Issue by spaquet** [mgbatchelor/atom-go-to-view#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.199.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.4
**Thrown From**: [go-to-view](https://github.com/mgbatchelor/atom-go-to-view) package, v0.1.2
### Stack Trace

Failed to activate the go-to-view package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (/Users/spaquet/.atom/packages/go-to-view/lib/go-to-view.js:7:23)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:238:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:219:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:211:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:435:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:419:29
  at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:414:19)
  at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:395:46)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:636:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:91:23)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:32:7)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-erlang",
      "language-elixir",
      "language-objective-c",
      "language-prolog",
      "language-sass",
      "archive-view",
      "background-tips",
      "coffee-lint",
      "feedback",
      "emmet",
      "image-view",
      "open-on-github",
      "autocomplete-plus",
      "autocomplete-snippets",
      "autocomplete-paths",
      "language-latex",
      "language-mustache",
      "language-x86",
      "language-go",
      "language-java",
      "language-make",
      "language-perl",
      "language-php",
      "language-toml"
    ],
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
.bin, vundefined
Sublime-Style-Column-Selection, v1.2.3
angularjs, v0.1.0
atom-prettify, v0.1.0
atom-rails, v0.4.0
auto-update-packages, v0.2.2
git-review, v0.2.1
go-to-view, v0.1.2
language-blade, v0.14.0
minimap, v4.9.0
minimap-find-and-replace, v4.2.0
node-debugger, v0.2.3
node-resolver, v1.0.1
pretty-json, v0.3.3
rails-navigation, v0.1.1
rails-rspec, v0.3.1
rsense, v0.6.0
ruby-block, v0.3.3
ruby-define-method, v0.2.0

# Dev
No dev packages
```

**Comment by mgbatchelor** [comment]
Updated packed to work with most recent version.
